MusicPortal/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Portal.BLL.DTO;
using Portal.BLL.Interfaces;
using MusicPortal.Filters;

namespace MusicPortal.Controllers
{
    [Culture]
    public class GenreController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IGenreService _context;
        private readonly ISongService _songService;
        public GenreController(IGenreService context, ISongService songService)
        {
            _context = context;
            _songService = songService;
        }
        public async Task <IActionResult> Index()
        {
            HttpContext.Session.SetString("path", Request.Path);
            return View(await _context.GetAllGenres());
        }
        public IActionResult Create()
        {
            HttpContext.Session.SetString("path", Request.Path);
            if (HttpContext.Session.GetInt32("Admin") == null)
            {
                HttpContext.Session.Clear();
                ViewBag.UserId = null;
            }
            return View();
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] GenreDTO gen)
        {
            GenreDTO genDto = await _context.GetGenreByName(gen.Name);
            if (genDto != null)
            {
                ModelState.AddModelError("", "Такой жанр есть!");
                return View(genDto);
            }
            genDto = new GenreDTO();
            if (ModelState.IsValid)
            {
                genDto.Name = gen.Name;
                await _context.CreateGenre(genDto);                
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);
            if (id == null)
            {
                return NotFound();
            }

            var gen = await _context.GetGenreById((int)id);
            if (gen == null)
            {
                return NotFound();
            }

            return View(gen);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {           
            GenreDTO gen = await _context.GetGenreById((int)id);
            var songs = await _songService.GetSongsByGenre(gen);
            if (songs != null)
            {
                foreach (var song in songs)
                {
                    await _songService.Delete(song.Id);
                }
            }
            if (gen != null)
            {
                await _context.DeleteGenre(id);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

MusicPortal/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;
using MusicPortal.Filters;
using MusicPortal.Models;
using Portal.BLL.DTO;
using Portal.BLL.Interfaces;

namespace MusicPortal.Controllers
{
    [Culture]
    public class SongController : Controller
    {
        private readonly ISongService _context;
        private readonly IGenreService _genreService;
        private readonly IWebHostEnvironment _appEnvironment; //рабочее окружение приложения

        public SongController(ISongService context, IGenreService genreService, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _genreService = genreService;
            _appEnvironment = webHostEnvironment;
        }
        public async Task <IActionResult> Index(string author, int genre = 0, int page = 1, SortState sortOrder = SortState.NameAsc)
        {
            HttpContext.Session.SetString("path", Request.Path);
            int pageSize = 5;
            IEnumerable<SongDTO> songs = await _context.GetAllSongs();
            //фильтрация
            if (genre != 0)
            {
                songs = songs.Where(s => s.GenreId == genre);
            }
            if (!string.IsNullOrEmpty(author))
            {
                songs =songs.Where(s => s.Author == author);
            }
            //сортировка

            songs = sortOrder switch
            {
                SortState.NameDesc => songs.OrderByDescending(s => s.Name),
                SortState.AuthorAsc => songs.OrderBy(s => s.Author),
                SortState.AuthorDesc => songs.OrderByDescending(s => s.Author),
                SortState.GenreAsc => songs.OrderBy(s => s.Genre),
                SortState.GenreDesc => songs.OrderByDescending(s => s.Genre),
                _ => songs.OrderBy(s => s.Name),
            };

            //пагинация
            var count = songs.Count();
            var items = songs.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // формируем модель представления
            var gen =await _genreService.GetAllGenres();
            List<GenreDTO> genres= gen.ToList();
            IndexViewModel viewModel = new IndexViewModel(
              items,
              new PageViewModel(count, page, pageSize),
              new SortViewModel(sortOrder),
              new FilterViewModel(genres, genre, author)              
          );
            return View(viewModel);
        }
        public async Task <IActionResult> Create()
        {
            HttpContext.Session.SetString("path", Request.Path);
            ViewBag.Genres = new SelectList(await _genreService.GetAllGenres(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestSizeLimit(1000000000)]
        public async Task<IActionResult> Create(SongDTO songDTO, IFormFile uploadedFile)
        {
            var songsByAuthor = await _context.GetSongsByAuthor(songDTO.Author!);
            SongDTO sdto = songsByAuthor.Where(s=>s.Name == songDTO.Name).FirstOrDefault();

            if (sdto != null)
            {
                ModelState.AddModelError("", "Такая песня есть!");
                return View(songDTO);
            }
            else
            {
                sdto = new SongDTO();
                if(ModelState.IsValid && uploadedFile != null)
                {
                        await UploadSong(songDTO, uploadedFile);
                        await _context.Create(songDTO);
                        return RedirectToAction("Index");

                }
            }
            ViewBag.Genres = new SelectList(await _genreService.GetAllGenres(), "Id", "Name", songDTO.GenreId);
           
            return RedirectToAction("Index");
        }
        private async Task UploadSong(SongDTO songDTO, IFormFile uploadedFile)
        {
                // Путь к папке 
                string path = "/data/" + uploadedFile.FileName; // имя файла
                songDTO.Path = path;
               
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
            
        }
        public async Task<IActionResult> Delete(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);
            if (id == null)
            {
                return NotFound();
            }
          
            var song = await _context.GetSongById((int)id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var song = await _context.GetSongById(id);
            if (song != null)
            {
                await _context.Delete(id);
            }
            TempData["Message"] = "Песня удалена!";
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);
            if (id == null)
            {
                return NotFound();
            }
            SongDTO song = await _context.GetSongById((int)id);
            if (song == null)
            {
                return NotFound();
            }
            ViewBag.ListGenres = new SelectList(await _genreService.GetAllGenres(), "Id", "Name", song.GenreId);
            return View(song);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SongDTO songDto)
        {
            if (id != songDto.Id)
            {
                return NotFound();
            }          
            if (ModelState.IsValid)
            {
                try
                {
                    await _context.Update(songDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
            }
            return View(songDto);
        }
        public ActionResult ChangeCulture(string lang)
        {
            string? returnUrl = HttpContext.Session.GetString("path") ?? "/Song/Index";

            // Список культур
            List<string> cultures = new List<string>() { "ru", "uk" };
            if (!cultures.Contains(lang))
            {
                lang = "ru";
            }

            CookieOptions option = new CookieOptions();
            option.Expires = DateTime.Now.AddDays(10); // срок хранения куки - 10 дней
            Response.Cookies.Append("lang", lang, option); // создание куки
            return Redirect(returnUrl);
        }
    }
}

MusicPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicPortal.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="header-container">
             <div class="col-1">

            @using (Html.BeginForm("ChangeCulture", "Song"))
            {
                <select name="lang" id="form-control">
                    <option value="ru">Русский</option>
                    <option value="uk">Українська</option>
                </select>
                <div>
                <input id="inputSel" type="submit" name="submit" value="@Resources.Resource.ChooseLang" class="btn">
                </div>
            }
             </div>
            
             <nav>
                 <div class="ndb">
                <a id="link-1" class="navbar-brand btn-new" asp-area="" asp-controller="Song" asp-action="Index">@Resources.Resource.Home</a>
			      </div>
                 <div class ="ndb">
                <a id="link-2" class="navbar-brand btn-new" asp-area="" asp-controller="Users" asp-action="Create">@Resources.Resource.Registration</a>
                  </div>
                  <div class="ndb">
                    @if (@Context.Session.GetString("Name") == null)
                     {
                    <a id="link-3" class="navbar-brand btn-new" asp-area="" asp-controller="Users" asp-action="Logon">@Resources.Resource.Entrance</a>
                     }
                    else
                     {
                    <a id="link-3" class="navbar-brand btn-new" asp-area="" asp-controller="Home" asp-action="Logout">@Resources.Resource.Exit</a>

                     }
                  </div>
			</nav>    
          
      
            <div class="panel-user">
               @if (@Context.Session.GetString("Name") != null)
              {
                <p class="user-panel" style="text-align:right; font-weight: bold; margin:5px; color:darkred;">@Resources.Resource.User_panel</p>
                <p class="user-panel-1" style="text-align:center; margin:5px">@Resources.Resource.Hello @Context.Session.GetString("Name")!</p>
                <p style="visibility: hidden; "></p>
                <p class="user-panel" style="display:inline; margin:5px">@Resources.Resource.Login:</p>
                <p class="user-panel-1" style="margin:5px"> (@Context.Session.GetString("Login"))</p>
                <p style="visibility: hidden;"></p>
                <p class="user-panel" style="display:inline;">@Resources.Resource.Status:</p>
                if (@Context.Session.GetInt32("Admin") == 1)
                {
                    <p class="user-panel-1">@Resources.Resource.Administrator</p>
                }
                else
                {
                    <p class="user-panel-1">@Resources.Resource.User</p>
                }
                <p style="visibility: hidden;"></p>
                <a class="navbar-brand btn-new" asp-controller="Users" asp-action="EditUser" asp-route-id="@Context.Session.GetInt32("Ident")">@Resources.Resource.Edit</a>
            }
            else
            {
                <p class="user-panel" style="text-align:right; font-weight: bold; margin:5px; color:darkred;">Регистрация дает <br /> больше возможностей</p>
            }
        </div>       
    </header>
   
    <div class="index-bg" style="background-image: url('/images/background.jpg');">
        <div id="index-col-1">
           
          
        </div>
        <main id="index-col-2" role="main" >
          
            @if (@Context.Session.GetInt32("Admin") == 1)
            {  
             <div id="admin-panel">
                    <a class="navbar-brand btn-new" asp-controller="Users" asp-action="Index">@Resources.Resource.Users</a>
                    <a class="navbar-brand btn-new" asp-controller="Genre" asp-action="Index">@Resources.Resource.Genres</a>
                    <a class="navbar-brand btn-new" asp-controller="Song" asp-action="Index">@Resources.Resource.Songs</a>
			 </div>
                <hr/>
            } 
         <div id="render-div">
            @RenderBody()
          </div>
        </main>
        <div id="index-col-3"></div>
    </div>
    <div style="height: 7px"></div>
    <footer class="footer">
       <div class="container">
            &copy; 2024 - MusicPortal all rights reserved!
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>